/*
Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license ( the "Software" ) to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:
The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module derelict.nvrtc;

/**
    Translation of nvrtc.h
*/

import derelict.util.loader;

private
{
    import derelict.util.system;

    static if(Derelict_OS_Windows)
        enum libNames = "nvrtc64_80.dll,nvrtc-builtins64_80.dll";
    else static if (Derelict_OS_Linux)
    {
        version(X86_64)
            enum libNames = "libnvrtc.so.8.0,libnvrtc.so,libnvrtc-builtins.so.8.0,libnvrtc-builtins.so";
        else
            static assert(0, "Need to implement NVRTC libNames for this arch.");
    }
    else
        static assert(0, "Need to implement NVRTC libNames for this operating system.");

    enum ftMixin = q{
        string[][string] functionTypes = [
            "nvrtcGetErrorString": ["const char *", "nvrtcResult"],
            "nvrtcVersion": ["nvrtcResult", "int *", "int *"],
            "nvrtcCreateProgram": ["nvrtcResult", "nvrtcProgram *", "const char *", "const char *", "int", "const char **",
                "const char **"],
            "nvrtcDestroyProgram": ["nvrtcResult", "nvrtcProgram *"],
            "nvrtcCompileProgram": ["nvrtcResult", "nvrtcProgram, int", "const char **"],
            "nvrtcGetPTXSize": ["nvrtcResult", "nvrtcProgram", "size_t *"],
            "nvrtcGetPTX": ["nvrtcResult", "nvrtcProgram", "char *"],
            "nvrtcGetProgramLogSize": ["nvrtcResult", "nvrtcProgram", "size_t *"],
            "nvrtcGetProgramLog": ["nvrtcResult", "nvrtcProgram", "char *"],
            "nvrtcAddNameExpression": ["nvrtcResult", "nvrtcProgram", "const char **"],
            "nvrtcGetLoweredName": ["nvrtcResult", "nvrtcProgram", "const char *", "const char **"]
        ];
    };

    string generateFunctionAliases()
    {
        import std.algorithm : joiner;
        import std.conv : to;

        mixin(ftMixin);

        string ret;

        foreach(fn, ft; functionTypes)
        {
            ret ~= "alias da_" ~ fn ~ " = " ~ ft[0] ~ " function(" ~ ft[1 .. $].joiner(",").to!string ~ ");";
        }

        return ret;
    }

    string generateFunctionPointers()
    {
        mixin(ftMixin);

        string ret;

        foreach(fn, ft; functionTypes)
        {
            ret ~= "da_" ~ fn ~ " " ~ fn ~ ";";
        }

        return ret;
    }

    string generateFunctionBinds()
    {
        mixin(ftMixin);

        string ret;

        foreach(fn, ft; functionTypes)
        {
            ret ~= "bindFunc(cast(void**)&" ~ fn ~ ", \"" ~ fn ~ "\");";
        }

        return ret;
    }
}

alias nvrtcResult = int;
enum : nvrtcResult
{
    NVRTC_SUCCESS = 0,
    NVRTC_ERROR_OUT_OF_MEMORY = 1,
    NVRTC_ERROR_PROGRAM_CREATION_FAILURE = 2,
    NVRTC_ERROR_INVALID_INPUT = 3,
    NVRTC_ERROR_INVALID_PROGRAM = 4,
    NVRTC_ERROR_INVALID_OPTION = 5,
    NVRTC_ERROR_COMPILATION = 6,
    NVRTC_ERROR_BUILTIN_OPERATION_FAILURE = 7,
    NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION = 8,
    NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION = 9,
    NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID = 10,
    NVRTC_ERROR_INTERNAL_ERROR = 11
}

struct _nvrtcProgram;
alias nvrtcProgram = _nvrtcProgram *;

extern(System) @nogc nothrow
{
    mixin(generateFunctionAliases());
}

__gshared
{
    mixin(generateFunctionPointers());
}

class DerelictNVRTCLoader : SharedLibLoader
{
    public
    {
        this()
        {
            super(libNames);
        }
    }

    protected
    {
        override void loadSymbols()
        {
            mixin(generateFunctionBinds());
        }
    }
}

__gshared DerelictNVRTCLoader DerelictNVRTC;

shared static this()
{
    DerelictNVRTC = new DerelictNVRTCLoader();
}

unittest
{
    DerelictNVRTC.load();

    int major, minor;
    nvrtcVersion(&major, &minor);

    import std.stdio : writeln;
    writeln("NVRTC version ", major, ".", minor);
}